processes: make get_process_by_listening port return a list
doronz88/rpc-project pull request #252
Opened 2023-01-08 15:12 UTC by yotamolenik

2023-01-08 15:45 UTC, doronz88 requested changes

2023-01-08 15:45 UTC, doronz88 commented on src/rpcclient/rpcclient/darwin/processes.py
> +    def get_process_by_listening_port(self, port: int) -> List[Process]:
`get_processes_by_listening_port`

2023-01-09 12:50 UTC, yotamolenik commented on src/rpcclient/rpcclient/darwin/processes.py
> +    def get_process_by_listening_port(self, port: int) -> List[Process]:
done

2023-01-09 17:11 UTC, doronz88 commented on src/rpcclient/rpcclient/darwin/processes.py
> +    def get_process_by_listening_port(self, port: int) -> List[Process]:
Fix commit message accordingly

2023-01-10 11:19 UTC, yotamolenik commented on src/rpcclient/rpcclient/darwin/processes.py
> +    def get_process_by_listening_port(self, port: int) -> List[Process]:
done

2023-01-10 14:15 UTC, doronz88 approved these changes

2023-01-10 14:15 UTC, merged